name: 'YAPF Python Code Formatting Check'
description: 'Run YAPF to check if your python code is correctly formatted.'
author: "Alexander Melde <alexander@melde.net>"

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  target_path:
    description: "Path of the files to lint.Seperate by space if you what to lint multi-directories"
    required: false
    default: "."
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  level:
    description: "Report level for reviewdog [info,warning,error]"
    required: false
    default: "error"
  reporter:
    description: "Reporter of reviewdog command [github-pr-check,github-pr-review]."
    required: false
    default: "github-pr-check"
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    required: false
    default: "nofilter"
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    required: false
    default: "false"
  reviewdog_flags:
    description: "Additional reviewdog flags"
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_TARGET_PATH: ${{ inputs.target_path }}
    INPUT_GITHUG_TOKEN: ${{ inputs.github_token }}
    INPUT_LEVEL: ${{ inputs.level }}
    INPUT_REPORTER: ${{ inputs.reporter }}
    INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
    INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
    INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}